In [82]:
# Write a function to compute 5/0 and use try/except to catch the exceptions

a = 5 
b = 0
try :
    a / b 
except : 
    print("An exception has  occured ")
else :
        print("No problem")

Some error occured 


In [79]:
# Implement a Python program to generate all sentences

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

sentences = [print("{} {} {}." .format(sub,ver,obj) )   for sub in subjects    for ver in verbs for obj in objects  ] 


Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


In [173]:
#Write a function so that the columns of the output matrix are powers of the input vector

import numpy as np


x = np.array([1,2,3,5])
N = 3 
print("(x,N) =\n", np.vander(x,N))  
print("\n(x) =\n", np.vander(x) )
print("\n(x,N,increasing=True) =\n",  np.vander(x,N,increasing=True) ) 
print("\n(x,N,increasing=False) =\n", np.vander(x,N,increasing=False) )



(x,N) =
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]

(x) =
 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]

(x,N,increasing=True) =
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]]

(x,N,increasing=False) =
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
